"""Consumer Copilot protocol frame helpers."""


def set_options_frame() -> dict[str, object]:
    return {
        "ads": {
            "supportedTypes": [
                "text",
                "product",
                "multimedia",
                "tourActivity",
                "propertyPromotion",
            ]
        },
        "event": "setOptions",
        "supportedActions": [],
        "supportedCards": [
            "weather",
            "local",
            "image",
            "sports",
            "video",
            "healthcareEntity",
            "healthcareInfo",
            "healthRecordsConnectNewProvider",
            "healthRecordsUpdate",
            "suggestHealth",
            "chart",
            "ads",
            "safetyHelpline",
            "quiz",
            "finance",
            "recipe",
            "personalArtifacts",
            "flashcard",
            "navigation",
            "person",
            "powerPointCreator",
            "consentV2",
            "composeEmail",
            "createCalendarEvent",
            "modifyCalendarEvent",
            "deleteCalendarEvent",
            "practiceTest",
            "tapToReveal",
        ],
        "supportedFeatures": [
            "partial-generated-images",
            "composer-prefill-conversation-action",
            "composer-send-conversation-action-v2",
            "side-by-side-comparison",
            "session-duration-nudge",
            "compose-email-html",
        ],
        "supportedUIComponents": {
            "Badge": "1.2",
            "Basic": "1.2",
            "Box": "1.2",
            "Button": "1.2",
            "Caption": "1.2",
            "Card": "1.2",
            "Chart": "1.2",
            "Checkbox": "1.2",
            "Col": "1.2",
            "DatePicker": "1.3",
            "Divider": "1.2",
            "Form": "1.2",
            "Icon": "1.2",
            "Image": "1.2",
            "Label": "1.2",
            "ListView": "1.2",
            "ListViewItem": "1.2",
            "Map": "1.3",
            "Markdown": "1.2",
            "Pressable": "1.3",
            "RadioGroup": "1.3",
            "Row": "1.2",
            "Select": "1.3",
            "Spacer": "1.2",
            "Table": "1.3",
            "Table.Cell": "1.3",
            "Table.Row": "1.3",
            "Text": "1.2",
            "Textarea": "1.3",
            "Title": "1.2",
            "Transition": "1.2",
        },
    }
